füge aramäisch mit babylonischer Punktation als eigene Sprache hinzu
revilovs/fth-latex pull request #9
Opened 2024-03-12 17:23 UTC by pico40

Aramäisch gibt es leider nicht als eigene Sprache bei polyglossia. Syriac ist ein aramäischer Dialekt, daher fand ich das halbwegs passend als Sprache zu verwenden und einfach die passende Schrift zu ergänzen.
Wenn in der Zukunft jemand mit Syriac arbeiten will, muss das ggf. nochmal angepasst werden.

2024-03-13 09:19 UTC, revilovs requested changes

2024-03-13 09:19 UTC, revilovs commented on fth/fth-lang.sty
> +	}
Hier wäre zur Sicherheit noch ein leeres `{}` als False-Branch sinnvoll

2024-04-06 14:20 UTC, pico40 commented on fth/fth-lang.sty
> +	}
done

2024-04-07 11:11 UTC, revilovs approved these changes

2024-04-07 11:11 UTC, merged